import { StyleSheet } from "react-native";

// Elegant color palette
const colors = {
	primary: "#6366f1", // Modern indigo
	primaryLight: "#818cf8",
	primaryDark: "#4f46e5",
	secondary: "#f59e0b", // Warm amber
	secondaryLight: "#fbbf24",
	secondaryDark: "#d97706",
	background: "#0f172a", // Deep slate
	surface: "#1e293b", // Lighter slate
	surfaceLight: "#334155",
	text: "#f8fafc", // Light gray
	textSecondary: "#cbd5e1",
	textMuted: "#64748b",
	success: "#10b981", // Emerald
	error: "#ef4444", // Red
	warning: "#f59e0b", // Amber
	border: "#334155",
	borderLight: "#475569",
	white: "#ffffff",
	black: "#000000",
};

// Typography scale
const typography = {
	h1: { fontSize: 32, fontWeight: "700" as const },
	h2: { fontSize: 28, fontWeight: "600" as const },
	h3: { fontSize: 24, fontWeight: "600" as const },
	h4: { fontSize: 20, fontWeight: "500" as const },
	body: { fontSize: 16, fontWeight: "400" as const },
	bodyBold: { fontSize: 16, fontWeight: "600" as const },
	caption: { fontSize: 14, fontWeight: "400" as const },
	captionBold: { fontSize: 14, fontWeight: "600" as const },
	small: { fontSize: 12, fontWeight: "400" as const },
};

// Spacing scale
const spacing = {
	xs: 4,
	sm: 8,
	md: 16,
	lg: 24,
	xl: 32,
	xxl: 48,
};

// Border radius
const borderRadius = {
	sm: 6,
	md: 12,
	lg: 16,
	xl: 24,
	full: 9999,
};

export const formStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: colors.background,
	},
	contentContainer: {
		padding: spacing.lg,
		paddingBottom: spacing.xxl,
	},
	header: {
		...typography.h2,
		color: colors.text,
		marginBottom: spacing.xl,
		textAlign: "center",
		letterSpacing: -0.5,
	},
	subtitle: {
		...typography.body,
		color: colors.textSecondary,
		textAlign: "center",
		marginBottom: spacing.xl,
		lineHeight: 24,
	},
	input: {
		backgroundColor: colors.surface,
		borderWidth: 1,
		borderColor: colors.border,
		borderRadius: borderRadius.md,
		padding: spacing.md,
		marginBottom: spacing.md,
		fontSize: typography.body.fontSize,
		color: colors.text,
		minHeight: 56,
		justifyContent: "center",
	},
	inputFocused: {
		borderColor: colors.primary,
		backgroundColor: colors.surfaceLight,
	},
	inputPlaceholder: {
		color: colors.textMuted,
	},
	button: {
		backgroundColor: colors.primary,
		paddingVertical: spacing.md,
		paddingHorizontal: spacing.lg,
		borderRadius: borderRadius.md,
		alignItems: "center",
		marginTop: spacing.lg,
		minHeight: 56,
		justifyContent: "center",
		shadowColor: colors.primary,
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.3,
		shadowRadius: 8,
		elevation: 8,
	},
	buttonPressed: {
		backgroundColor: colors.primaryDark,
		transform: [{ scale: 0.98 }],
	},
	buttonText: {
		color: colors.white,
		fontSize: typography.bodyBold.fontSize,
		fontWeight: typography.bodyBold.fontWeight,
		letterSpacing: 0.5,
	},
	nextButton: {
		backgroundColor: colors.success,
		paddingVertical: spacing.md,
		paddingHorizontal: spacing.lg,
		borderRadius: borderRadius.md,
		alignItems: "center",
		marginTop: spacing.lg,
		minHeight: 56,
		justifyContent: "center",
		shadowColor: colors.success,
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.3,
		shadowRadius: 8,
		elevation: 8,
	},
	nextButtonText: {
		color: colors.white,
		fontSize: typography.bodyBold.fontSize,
		fontWeight: typography.bodyBold.fontWeight,
		letterSpacing: 0.5,
	},
	backButton: {
		backgroundColor: colors.surface,
		borderWidth: 1,
		borderColor: colors.border,
		paddingVertical: spacing.md,
		paddingHorizontal: spacing.lg,
		borderRadius: borderRadius.md,
		alignItems: "center",
		marginTop: spacing.sm,
		minHeight: 56,
		justifyContent: "center",
	},
	backButtonText: {
		color: colors.textSecondary,
		fontSize: typography.bodyBold.fontSize,
		fontWeight: typography.bodyBold.fontWeight,
	},
	homeButton: {
		backgroundColor: colors.secondary,
		paddingVertical: spacing.md,
		paddingHorizontal: spacing.lg,
		borderRadius: borderRadius.md,
		alignItems: "center",
		marginTop: spacing.sm,
		minHeight: 56,
		justifyContent: "center",
		shadowColor: colors.secondary,
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.3,
		shadowRadius: 8,
		elevation: 8,
	},
	homeButtonText: {
		color: colors.white,
		fontSize: typography.bodyBold.fontSize,
		fontWeight: typography.bodyBold.fontWeight,
		letterSpacing: 0.5,
	},
	pickerContainer: {
		backgroundColor: colors.surface,
		borderWidth: 1,
		borderColor: colors.border,
		borderRadius: borderRadius.md,
		padding: spacing.md,
		marginBottom: spacing.md,
	},
	colorOption: {
		padding: spacing.md,
		borderRadius: borderRadius.sm,
		marginVertical: spacing.xs,
		borderWidth: 1,
		borderColor: colors.border,
		backgroundColor: colors.surface,
	},
	selectedOption: {
		backgroundColor: colors.primary,
		borderColor: colors.primary,
	},
	colorOptionText: {
		fontSize: typography.body.fontSize,
		color: colors.text,
		textAlign: "center",
	},
	selectedOptionText: {
		color: colors.white,
		fontWeight: typography.bodyBold.fontWeight,
	},
	starContainer: {
		flexDirection: "row",
		justifyContent: "center",
		marginBottom: spacing.xl,
		paddingHorizontal: spacing.md,
	},
	starButton: {
		padding: spacing.sm,
		marginHorizontal: spacing.xs,
		borderRadius: borderRadius.full,
	},
	selectedStar: {
		backgroundColor: colors.secondary,
		shadowColor: colors.secondary,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.3,
		shadowRadius: 4,
		elevation: 4,
	},
	starText: {
		fontSize: 32,
		color: colors.textMuted,
	},
	selectedStarText: {
		color: colors.white,
	},
	ratingText: {
		color: colors.text,
		fontSize: typography.body.fontSize,
		textAlign: "center",
		marginBottom: spacing.xl,
		lineHeight: 24,
	},
	emojiContainer: {
		flexDirection: "row",
		flexWrap: "wrap",
		justifyContent: "center",
		marginBottom: spacing.xl,
		paddingHorizontal: spacing.md,
	},
	emojiOption: {
		padding: spacing.md,
		margin: spacing.xs,
		borderRadius: borderRadius.md,
		backgroundColor: colors.surface,
		borderWidth: 1,
		borderColor: colors.border,
		minWidth: 60,
		alignItems: "center",
	},
	selectedEmoji: {
		backgroundColor: colors.secondary,
		borderColor: colors.secondary,
		shadowColor: colors.secondary,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.3,
		shadowRadius: 4,
		elevation: 4,
	},
	emojiText: {
		fontSize: 28,
	},
	progressContainer: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginBottom: spacing.xl,
		paddingHorizontal: spacing.lg,
	},
	progressStep: {
		width: 32,
		height: 32,
		borderRadius: borderRadius.full,
		backgroundColor: colors.surface,
		borderWidth: 2,
		borderColor: colors.border,
		alignItems: "center",
		justifyContent: "center",
	},
	progressStepActive: {
		backgroundColor: colors.primary,
		borderColor: colors.primary,
		shadowColor: colors.primary,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.3,
		shadowRadius: 4,
		elevation: 4,
	},
	progressStepCompleted: {
		backgroundColor: colors.success,
		borderColor: colors.success,
	},
	progressStepText: {
		color: colors.white,
		fontSize: typography.small.fontSize,
		fontWeight: typography.captionBold.fontWeight,
	},
	progressStepTextInactive: {
		color: colors.textMuted,
	},
	card: {
		backgroundColor: colors.surface,
		borderRadius: borderRadius.lg,
		padding: spacing.lg,
		marginBottom: spacing.md,
		borderWidth: 1,
		borderColor: colors.border,
		shadowColor: colors.black,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 8,
		elevation: 4,
	},
	modalOverlay: {
		flex: 1,
		backgroundColor: "rgba(0, 0, 0, 0.6)",
		justifyContent: "center",
		alignItems: "center",
		padding: spacing.lg,
	},
	modalContent: {
		backgroundColor: colors.surface,
		borderRadius: borderRadius.lg,
		padding: spacing.xl,
		width: "100%",
		maxWidth: 400,
		shadowColor: colors.black,
		shadowOffset: { width: 0, height: 10 },
		shadowOpacity: 0.3,
		shadowRadius: 20,
		elevation: 10,
	},
	modalHeader: {
		...typography.h3,
		color: colors.text,
		marginBottom: spacing.lg,
		textAlign: "center",
	},
	modalOption: {
		padding: spacing.md,
		borderRadius: borderRadius.sm,
		marginVertical: spacing.xs,
		backgroundColor: colors.surfaceLight,
	},
	modalOptionText: {
		fontSize: typography.body.fontSize,
		color: colors.text,
		textAlign: "center",
	},
	divider: {
		height: 1,
		backgroundColor: colors.border,
		marginVertical: spacing.md,
	},
	badge: {
		backgroundColor: colors.primary,
		paddingHorizontal: spacing.sm,
		paddingVertical: spacing.xs,
		borderRadius: borderRadius.full,
		alignSelf: "flex-start",
	},
	badgeText: {
		color: colors.white,
		fontSize: typography.small.fontSize,
		fontWeight: typography.captionBold.fontWeight,
	},
	colorContainer: {
		marginBottom: spacing.xl,
	},
	emptyState: {
		backgroundColor: colors.surface,
		borderRadius: borderRadius.lg,
		padding: spacing.xl,
		alignItems: "center",
		borderWidth: 1,
		borderColor: colors.border,
		marginBottom: spacing.lg,
	},
	emptyStateText: {
		...typography.body,
		color: colors.textSecondary,
		textAlign: "center",
		lineHeight: 24,
		marginBottom: spacing.lg,
	},
});
